apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>My Nginx Page</title>
    </head>
    <body>
        <h1>안녕하세요! test server 1!.</h1>
    </body>
    </html>
